cxcontainer/cxdiagnosis/urls.py
from django.urls import include, path
# from cxdiagnosis import views
from cxdiagnosis.views import cxdiagnosis, clientuser, csguser, cxsuperuser
# from django.conf.urls.import url, patterns

urlpatterns = [
    path('', cxdiagnosis.home, name='home'),
    path('passwd/', cxdiagnosis.change_password, name='change_password'),
    path('changeit/', cxdiagnosis.check_first, name='check_first'),

    path('clientuser/', include(([
        path('', clientuser.CapabilityListView.as_view(),
            name='capability_list'),
        # path('domains/', clientuser.ClientUserDomainView.as_view(),
        #     name='clientuser_domains'),
        path('completed/', clientuser.CompletedCapabilitylistView.as_view(),
            name='completed_capability_list'),
        path('downloadpdf/<int:pk>/', clientuser.write_pdf_view,
            name='download_pdf'),
        path('editcapability/<int:pk>/<int:editqno>/<int:pgid>/<int:isprev>/<int:isnex>/', clientuser.edit_completed_capability,
            name='edit_completed_capability'),
        path('capability/<int:pk>/', clientuser.completed_capability,
            name='completed_capability'),
    ], 'cxdiagnosis'), namespace='clientuser')),

    # url('downloadpdf/', clientuser.DownloadPDF.as_view(), name='download_pdf'),

    path('csguser/', include(([
        path('', csguser.CapabilityList.as_view(),
            name='capability_list'),
        path('completed/', csguser.CompletedCapabilitylistView.as_view(),
            name='completed_capability_list'),
        path('completed/domainwise/', csguser.DomainCompletedCapabilitylistView.as_view(),
            name='csg_domain_completed_capabilities'),
        path('downloadpdf/<int:pk>/', csguser.write_pdf_view,
            name='download_pdf'),
        path('editcapability/<int:pk>/<int:editqno>/<int:pgid>/<int:isprev>/<int:isnex>/', csguser.edit_completed_capability,
            name='edit_completed_capability'),
        path('capability/<int:pk>/', csguser.completed_capability,
            name='completed_capability'),
        path('capability/', csguser.CapabilityUpdateList.as_view(),
            name='update_list_capability'),
        path('capability/new/', csguser.CreateCapabilityView.as_view(),
            name='new_capability'),
        path('capability/<int:pk>/', csguser.UpdateCapabilityView.as_view(),
            name='update_capability'),
        path('capability/<int:pk>/completed/', csguser.CompletedCapabilityView.as_view(),
            name='completed_capability_view'),
        path('capability/<int:pk>/delete/', csguser.DeleteCapabilityView.as_view(),
            name='delete_capability'),
        path('capability/<int:pk>/question/add/', csguser.question_add,
            name='question_add'),
        path('capability/<int:capability_pk>/question/<int:question_pk>/', csguser.question_change,
            name='question_change'),
        path('capability/<int:capability_pk>/question/<int:question_pk>/delete/', csguser.QuestionDeleteView.as_view(),
            name='question_delete'),
    ], 'cxdiagnosis'), namespace='csguser')),

    path('cxsuperuser/', include(([
        path('', cxsuperuser.CxSuCapabilityList.as_view(), name='cx_su_update_list_capability'),
        path('capability/new/', cxsuperuser.CreateCapabilityView.as_view(), name='cx_su_new_capability'),
        path('capability/allresults/', cxsuperuser.AllResults.as_view(), name='cx_su_view_completed'),
        path('capability/<int:pk>/', cxsuperuser.UpdateCapabilityView.as_view(), name='cx_su_update_capability'),
        path('capability/<int:pk>/completed/', cxsuperuser.CompletedCapabilityView.as_view(), name='cx_su_completed_capability'),
        path('capability/<int:pk>/delete/', cxsuperuser.DeleteCapabilityView.as_view(), name='cx_su_delete_capability'),
        path('capability/<int:pk>/question/add/', cxsuperuser.question_add, name='question_add'),
        path('capability/<int:capability_pk>/question/<int:question_pk>/', cxsuperuser.question_change, name='question_change'),
        path('capability/<int:capability_pk>/question/<int:question_pk>/delete/', cxsuperuser.QuestionDeleteView.as_view(), name='question_delete'),
    ], 'cxdiagnosis'), namespace='cxsuperuser')),

]

cxcontainer/cxproject/urls.py
# from django.contrib import admin
from django.urls import include, path
# from cxdiagnosis import views
from cxdiagnosis.views import cxdiagnosis, clientuser, cxsuperuser, csguser

urlpatterns = [
    path('', include('cxdiagnosis.urls')),
    path('cxaccounts/', include('django.contrib.auth.urls')),
    # path('cxaccounts/signup/', cxdiagnosis.SignUpView.as_view(), name='signup'),
    path('cxaccounts/client/signup/', clientuser.ClientUserSignUpView.as_view(), name='client_signup'),
    path('cxaccounts/ajax/load-operatinggroups/', cxdiagnosis.load_operatinggroups, name='ajax_load_operatinggroups'),
    path('cxaccounts/ajax/load-industrygroups/', cxdiagnosis.load_industrygroups, name='ajax_load_industrygroups'),
    path('cxaccounts/ajax/load-deliverygroups/', cxdiagnosis.load_deliverygroups, name='ajax_load_deliverygroups'),
    path('cxaccounts/ajax/load-accounts/', cxdiagnosis.load_accounts, name='ajax_load_accounts'),
    path('cxaccounts/ajax/load-deliveryunits/', cxdiagnosis.load_deliveryunits, name='ajax_load_deliveryunits'),
    path('cxaccounts/ajax/load-projects/', cxdiagnosis.load_projects, name='ajax_load_projects'),
    path('cxaccounts/csg/signup/', csguser.CsgUserSignUpView.as_view(), name='csg_signup'),
    path('cxaccounts/cxadmin/signup/', cxsuperuser.CxSuperUserSignUpView.as_view(), name='cxsuper_signup'),

]

cxcontainer/cxdiagnosis/views/clientuser.py
import os
import time
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.shortcuts import redirect, render
from django.db.models import Count, Sum, Max
from django.forms import modelformset_factory
from django.contrib import messages
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from ..models import ClientUser, User, Capability, CompletedCapability, Question, Answer, MaturityLevel, ClientUserAnswer
from ..forms import ClientUserSignUpForm, CompletedCapabilityForm
# , ClientUserDomainForm
from ..decorators import clientuser_required
# from easy_pdf.views import PDFTemplateView
# from django_xhtml2pdf.views import PdfMixin
# from xhtml2pdf import pisa

# below packages are to generate pdf using reportlab
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
temp_dir = BASE_DIR + "\\..\\static\\temp"

class ClientUserSignUpView(CreateView):
    model = User
    form_class = ClientUserSignUpForm
    template_name = 'registration/signup_form.html'
    # success_url = reverse_lazy('client_signup')

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'clientuser'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        # return redirect('home')
        return redirect('clientuser:capability_list')

# @method_decorator([login_required, clientuser_required], name='dispatch')
# class ClientUserDomainView(UpdateView):
#     model = ClientUser
#     form_class = ClientUserDomainForm
#     template_name = 'clientuser/domains_form.html'
#     success_url = reverse_lazy('clientuser:capability_list')
#
#     def get_object(self):
#         return self.request.user.clientuser
#
#     def form_valid(self, form):
#         messages.success(self.request, 'Interests updated with success!')
#         return super().form_valid(form)


@method_decorator([login_required, clientuser_required], name='dispatch')
class CapabilityListView(ListView):
    model = Capability
    ordering = ('name', )
    context_object_name = 'capabilities'
    template_name = 'clientuser/capability_list.html'

    def get_queryset(self):
        clientuser = self.request.user.clientuser
        # clientuser_domains = clientuser.domains
        # .values_list('pk', flat=True)
        # completed_capabilities = clientuser.capabilities.values_list(
        #     'pk', flat=True)
        completed_capability_ids = []
        for i in clientuser.capabilities.values_list('pk',flat=True).distinct():
            if not clientuser.get_unanswered_questions(get_object_or_404(Capability, pk=i)).exists():
                completed_capability_ids.append(i)
        queryset = Capability.objects \
            .exclude(pk__in=completed_capability_ids) \
            .annotate(questions_count=Count('questions')) \
            .filter(questions_count__gt=0)
        return queryset

@method_decorator([login_required, clientuser_required], name='dispatch')
class CompletedCapabilitylistView(ListView):
    model = CompletedCapability
    context_object_name = 'completed_capabilities'
    template_name = 'clientuser/completed_capability_list.html'

    # def get_queryset(self):
    #     queryset = self.request.user.clientuser.completed_capabilities \
    #         .select_related('capability') \
    #         .order_by('capability__name')
    #     return queryset

    # def get_queryset(self):
    #     queryset = self.request.user.clientuser.completed_capabilities \
    #         .values('capability__name') \
    #         .annotate(total=Sum('score'), qcount=Count('question'))
    #     return queryset

    def get_context_data(self, **kwargs):
        context = super(CompletedCapabilitylistView, self).get_context_data(**kwargs)
        context['completedCap'] = self.request.user.clientuser.completed_capabilities \
            .values('capability__name') \
            .annotate(total=Sum('score'), qcount=Count('question'), completion_date=Max('date'))
        context['totQ'] = Capability.objects.values('name').annotate(qcount=Count('questions'))
        return context

    def get_queryset(self):
        return 0
# @method_decorator([login_required, clientuser_required], name='dispatch')
# class DownloadPDF(PdfMixin, DetailView):
#     template_name = 'clientuser/download_pdf.html'


# @method_decorator([login_required, clientuser_required], name='dispatch')
# class DownloadPDF(PdfMixin, DetailView):
#     model = CompletedCapability
#     template_name = 'clientuser/download_pdf.html'

@login_required
@clientuser_required
def write_pdf_view(request, pk):
    # capability = get_object_or_404(CompletedCapability)
    # clientuser = request.user.clientuser
    # request.user.clientuser
    doc = SimpleDocTemplate(temp_dir + "\\clientuser_data.pdf")
    styles = getSampleStyleSheet()
    Story = [Spacer(1, 2*inch)]
    style = styles["Normal"]

    header_line = ('''<span><font size="10" color=black><b>  Capability Area  </b></font><font size="10" color=gray><b>  Capability  </b></font><font size="10" color=black><b>  Score  </b></font><font size="10" color=gray><b>  Date  </b></font></span>''')
    p = Paragraph(header_line, style)
    Story.append(p)
    Story.append(Spacer(1, 0.2*inch))
    # ca = None
    for completed_capability in CompletedCapability.objects.all():
        if completed_capability.clientuser_id == pk:
            # if ca == None:
            #     formated_string = (''' %30s %100s
            #                        %400s %10s ''' %
            #                        (completed_capability.date, completed_capability.capability, completed_capability.question, completed_capability.score))
            #     p = Paragraph(formated_string, style)
            #     ca = completed_capability.capability
            # elif ca == completed_capability.capability:
            #     formated_string = (''' %400s %10s ''' %
            #                        (completed_capability.question, completed_capability.score))
            #     p = Paragraph(formated_string, style)
            # else:
            #     formated_string = (''' %30s %100s
            #                        %400s %10s ''' %
            #                        (completed_capability.date, completed_capability.capability, completed_capability.question, completed_capability.score))
            #     p = Paragraph(formated_string, style)
            #     ca = completed_capability.capability

            formated_string = ('''<span> <font size="8" color=black>%100s</font>     <font size="8" color=gray>%400s</font>   <font size="8" color=black><i>%30s</i></font>   <font size="8" color=gray>%10s</font>  </span>''' %
                               (completed_capability.capability, completed_capability.question, completed_capability.score, completed_capability.date))
            p = Paragraph(formated_string, style)
            Story.append(p)
            Story.append(Spacer(1, 0.2*inch))
    # ca = None
    doc.build(Story)

    fs = FileSystemStorage(temp_dir)
    with fs.open("clientuser_data.pdf") as pdf:
        response = HttpResponse(pdf, content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="clientuser_data.pdf"'
        # response['Content-Disposition'] = 'inline; filename="mypdf.pdf"'
        return response

    return response

# class DownloadPDF(ListView):
#     model = CompletedCapability
#     context_object_name = 'completed_capabilities'
#     template_name = 'clientuser/download_pdf.html'
#
#     def get_queryset(self):
#         queryset = self.request.user.clientuser.completed_capabilities \
#             .select_related('capability') \
#             .order_by('capability__name')
#         return queryset


# @login_required
# @clientuser_required
# def new_product(request):
#     if request.method == 'POST':
#         form = StartAllCapabilitiesForm(request.user, request.POST)
#         if form.is_valid():
#             product = form.save(commit=False)
#             product.user = request.user
#             product.save()
#             return redirect('clientuser:capability_list')
#     else:
#         form = StartAllCapabilitiesForm(request.user)
#     return render(request, 'clientuser/completed_capability_form.html', {'form': form})

# @login_required
# @clientuser_required
# def start_all_capablilities(request, pk):
#     ProductFormSet = modelformset_factory(Capability, fields=('owner', ), extra=0)
#     data = request.POST or None
#     # formset = ProductFormSet(data=data, queryset=Product.objects.filter(user=request.user))
#     # for form in formset:
#     #     form.fields['category'].queryset = Category.objects.filter(user=request.user)
#
#     formset = ProductFormSet(data=data, queryset=Question.objects.filter(capability__owner=pk))
#     for form in formset:
#         form.fields['answer'].queryset = Answer.objects.filter(question__capability__owner=pk)
#
#     if request.method == 'POST' and formset.is_valid():
#         formset.save()
#         return redirect('clientuser:capability_list')
#
#     return render(request, 'clientuser/completed_capability_formset.html', {'formset': formset})

@login_required
@clientuser_required
def edit_completed_capability(request, pk, editqno, pgid, isprev, isnex):
    capability = get_object_or_404(Capability, pk=pk)
    clientuser = request.user.clientuser

    total_questions = capability.questions.count()

cxcontainer/cxdiagnosis/templates/clientuser/_header.html
<p class="text-info">
  <strong>Delivory Unit: </strong><span class="badge badge-pill badge-dark"> {{ user.clientuser.deliveryunit }}</span>
  <strong>Project: </strong><span class="badge badge-pill badge-secondary"> {{ user.clientuser.project }}</span>
</p>
<ul class="nav nav-tabs mb-3">
  <li class="nav-item">
    <a class="nav-link{% if active == 'new' %} active{% endif %}" href="{% url 'clientuser:capability_list' %}">New</a>
  </li>
  <li class="nav-item">
    <a class="nav-link{% if active == 'completed' %} active{% endif %}" href="{% url 'clientuser:completed_capability_list' %}">Completed</a>
  </li>
</ul>

cxcontainer/cxdiagnosis/templates/clientuser/capability_area_list.html
{% extends 'base.html' %}

{% block content %}
  {% if user.change_pass %}
    <a href="{% url 'change_password' %}">Required change password</a>
  {% else %}
    {% include 'clientuser/_header.html' with active='new' %}
    <div class="card">
      <a>Client user</a>
      <table class="table mb-0">
        <thead>
          <tr>
            <th>Capabiluty Area</th>
            <th>Domain</th>
            <th>Length</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for quiz in quizzes %}
            <tr>
              <td class="align-middle">{{ capabilityarea.name }}</td>
              <td class="align-middle">{{ capabilityarea.domain.get_html_badge }}</td>
              <td class="align-middle">{{ capabilityarea.questions_count }} questions</td>
              <td class="text-right">
                <a href="{% url 'clientuser:result_of_capability_areas' quiz.pk %}" class="btn btn-primary">Start quiz</a>
              </td>
            </tr>
          {% empty %}
            <tr>
              <td class="bg-light text-center font-italic" colspan="4">No capability matching your domain right now.</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% endif %}
{% endblock %}

cxcontainer/cxdiagnosis/templates/clientuser/capability_list.html
{% extends 'base.html' %}

{% block content %}
  {% if user.change_pass %}
    <a href="{% url 'change_password' %}">Required change password</a>
  {% else %}
    {% include 'clientuser/_header.html' with active='new' %}
    <div class="card">
      <table class="table mb-0">
        <thead>
          <tr>
            <th>Capability Area</th>
            <th>No of Capability</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for capability in capabilities %}
            <tr>
              <td class="align-middle">{{ capability.name }}</td>
              <td class="align-middle">{{ capability.questions_count }} capabilities</td>
              <td class="text-right">
                <a href="{% url 'clientuser:completed_capability' capability.pk %}" class="btn btn-primary">Start now</a>
              </td>
            </tr>
          {% empty %}
            <tr>
              <td class="bg-light text-center font-italic" colspan="4">No capability matching your domain right now.</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% endif %}
{% endblock %}

cxcontainer/cxdiagnosis/templates/clientuser/completed_capability.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% if user.change_pass %}
    <a href="{% url 'change_password' %}">Required change password</a>
  {% else %}
    {% include 'clientuser/_header.html' with active='new' %}
    <div class="progress mb-3">
      <div class="progress-bar" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"></div>
    </div>
    <h2 class="mb-3">{{ capability.name }}</h2>
    <p class="lead">{{ question.text }}</p>
    <form method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Next →</button>
    </form>
  {% endif %}
{% endblock %}

cxcontainer/cxdiagnosis/templates/clientuser/completed_capability_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% if user.change_pass %}
    <a href="{% url 'change_password' %}">Required change password</a>
  {% else %}
    {% include 'clientuser/_header.html' with active='new' %}
    <div class="progress mb-3">
      <div class="progress-bar" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"></div>
    </div>
    <h4 class="mb-3">{{ capability.name }}</h4>
    <p class="lead">{{ question.text }}</p>
    <form method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      {% if form.answer.errors %}
        <p class="text-danger">Please select your maturity level !</p>
      {% endif %}
      {% if total_unanswered_questions != total_questions %}
        <a href="{% url 'clientuser:edit_completed_capability' capability.pk question.id 0 1 0 %}" class="btn btn-primary">← Previous</a>
      {% endif %}
      {% if progress == 100 %}
        <button type="submit" class="btn btn-primary">Save & Submit</button>
      {% else %}
        <button type="submit" class="btn btn-primary">Save & Next →</button>
      {% endif %}
    </form>
  {% endif %}
{% endblock %}

cxcontainer/cxdiagnosis/templates/clientuser/completed_capability_formset.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% if user.change_pass %}
    <a href="{% url 'change_password' %}">Required change password</a>
  {% else %}
    {% include 'clientuser/_header.html' with active='new' %}
    <div class="progress mb-3">
      <div class="progress-bar" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"></div>
    </div>
    <h2 class="mb-3">{{ capability.owner }}</h2>
    <p class="lead">{{ question.text }}</p>

    <form method="post">
      {% csrf_token %}
      {{ formset.as_p }}
      <input type="submit" value="save all Capabilities">
    </form>
  {% endif %}
{% endblock %}

cxcontainer/cxdiagnosis/templates/clientuser/completed_capability_list.html
{% extends 'base.html' %}

{% load crispy_forms_tags humanize %}

{% block content %}
  {% if user.change_pass %}
    <a href="{% url 'change_password' %}">Required change password</a>
  {% else %}
    {% include 'clientuser/_header.html' with active='completed' %}
    <div class="text-right">
      <a href="{% url 'clientuser:download_pdf' user.pk %}"> Download PDF</a>
    </div>
    <div class="card">
      <table class="table mb-0">
        <thead>
          <tr>
            <th>Capability Area</th>
            <th>Overall Maturity Level</th>
            <th>Completion Date & Time</th>
          </tr>
        </thead>
        <tbody>
          {% for completed_capability in completedCap %}
            <tr>
              {% for capQ in totQ %}
                {% if capQ.name == completed_capability.capability__name and capQ.qcount == completed_capability.qcount %}
                  <td>{{ completed_capability.capability__name }}</td>
                  {% if completed_capability.total < 1 %}
                    <td>Not started</td>
                  {% elif completed_capability.total < 6 %}
                    <td>Basic</td>
                  {% elif completed_capability.total < 11 %}
                    <td>Medium</td>
                  {% elif completed_capability.total < 16 %}
                    <td>Pro</td>
                  {% endif %}
                  <td>{{ completed_capability.completion_date|naturaltime }}</td>
                {% endif %}
              {% endfor %}
            </tr>
          {% empty %}
            <tr>
              <td class="bg-light text-center font-italic" colspan="3">You haven't completed any capability yet.</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  {% endif %}
{% endblock %}

cxcontainer/cxdiagnosis/templates/clientuser/edit_completed_capability_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  {% if user.change_pass %}
    <a href="{% url 'change_password' %}">Required change password</a>
  {% else %}
    {% include 'clientuser/_header.html' with active='new' %}
    <div class="progress mb-3">
      <div class="progress-bar" role="progressbar" aria-valuenow="{{ progress }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ progress }}%"></div>
    </div>
    <h3 class="mb-3">{{ capability.name }}</h3>
    <p class="lead">{{ question.text }}</p>
    <form method="post" novalidate>
      {% csrf_token %}
      {{ form|crispy }}
      {% if total_answered_questions != pgid %}
        <a href="{% url 'clientuser:edit_completed_capability' capability.pk question.id pgid 1 0 %}" class="btn btn-primary">← Previous</a>
      {% endif %}
      <button type="submit" class="btn btn-primary">Update & Next →</button>
    </form>
  {% endif %}
{% endblock %}